<?php

/**
 * templates\messageQueue.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

namespace TechDivision\Example\Servlets;

use TechDivision\Example\Utils\ContextKeys;
use TechDivision\Example\Utils\RequestKeys;

/** @var $this \TechDivision\Example\Servlets\LoginServlet */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="appserver.io">

    <title>appserver.io example</title>

    <base href="<?php echo $this->getBaseUrl() ?>">

    <link href="components/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="static/css/style.css" rel="stylesheet">
    <link href="static/img/favicon.png" rel="shortcut icon">
</head>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.do"><img src="static/img/appserver-io-example.png" alt="appserver.io example"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <p class="navbar-text"><?php if ($this->isLoggedIn()): ?>Logged in as: <strong><?php echo $this->getUsername() ?></strong>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="<?php echo $this->getLogoutLink() ?>">logout</a><?php else: ?>Not logged in.<?php endif; ?></p>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="index.do"><span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Home</a></li>
                    <li><a href="index.do/login"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Login</a></li>
                    <li><a href="index.do/upload"><span class="glyphicon glyphicon-upload"></span>&nbsp;&nbsp;Upload</a></li>
                    <li><a href="index.do/webSocket"><span class="glyphicon glyphicon-retweet"></span>&nbsp;&nbsp;WebSocket</a></li>
                    <li class="active"><a href="index.do/messageQueue"><span class="glyphicon glyphicon-list"></span>&nbsp;&nbsp;Message-Queue</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-briefcase"></span>&nbsp;&nbsp;&nbsp;Authentication <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="index.do/basicAuthentication">Basic</a></li>
                            <li><a href="index.do/digestAuthentication">Digest</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container content">

        <?php if ($errorMessages = $this->getAttribute(ContextKeys::ERROR_MESSAGES)): ?>
            <div class="alert alert-danger">
                <?php foreach ($errorMessages as $errorMessage): ?>
                    <?php echo $errorMessage ?><br/>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <a href="http://appserver.io">
            <img src="static/img/logo-black.png"/>
        </a>

        <br>

        <h1>Select file</h1>

        <br>

        <form class="form-center" role="form" action="index.do/messageQueue/upload" method="post" enctype="multipart/form-data">
            <input name="<?php echo RequestKeys::FILE_TO_UPLOAD ?>" type="file" class="form-control" placeholder="Filename" />
            <br/>
            <label class="checkbox" for="<?php echo RequestKeys::WATCH_DIRECTORY ?>">
                <input type="checkbox" name="<?php echo RequestKeys::WATCH_DIRECTORY ?>" value="true"> Watch directory
            </label>
            <br/>
            <button class="btn btn-lg btn-info btn-block" type="submit">Upload file</button>
        </form>

        <br><br>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->getAttribute(ContextKeys::OVERVIEW_DATA) as $importFile): ?>
                    <tr>
                        <td><?php echo $importFile ?></td>
                        <td><a href="<?php echo $this->getImportLink($importFile) ?>">Import</a></td>
                        <td><a href="<?php echo $this->getDeleteLink($importFile) ?>">Delete</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <div class="footer">
            <p>&copy; and built with pride by <a href="http://appserver.io" target="_blank">appserver.io</a></p>
        </div>

    </div>

    <!-- placed at the end of the document so the pages load faster -->
    <script src="components/jquery/jquery.min.js"></script>
    <script src="components/bootstrap/js/bootstrap.min.js"></script>

</body>
</html>