<?php

/**
 * dhtml/elements/navigation.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

namespace AppserverIo\Apps\Example\Servlets;

use AppserverIo\Apps\Example\Utils\ViewHelper;
use AppserverIo\Apps\Example\Utils\RequestKeys;

?>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.do"><img src="static/img/appserver-io-example.png" alt="appserver.io example"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <p class="navbar-text"><?php if (ViewHelper::singleton()->isLoggedIn($servletRequest)) { ?>
                        Welcome <strong><?php echo ViewHelper::singleton()->getUsername($servletRequest) ?></strong>!&nbsp;&nbsp;|&nbsp;&nbsp;<a href="<?php echo ViewHelper::singleton()->getLogoutLink() ?>">logout</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="<?php echo ViewHelper::singleton()->getUserEditLink() ?>">edit</a>
                    <?php } else { ?>
                        <a href="<?php echo ViewHelper::singleton()->getSignInLink() ?>">Sign In</a> or <a href="<?php echo ViewHelper::singleton()->getCreateAccountLink() ?>">Create an Account</a>
                    <?php } ?></p>
                </li>
            </ul>
        </div>
    </div>
</div>